# Generated by Django 2.2.6 on 2019-11-01 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_comment', models.TextField()),
                ('comment_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
